-- MySQL Script generated by MySQL Workbench
-- Fri Nov 21 20:13:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mazdadb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mazdadb` ;

-- -----------------------------------------------------
-- Schema mazdadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mazdadb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mazdadb` ;

-- -----------------------------------------------------
-- Table `mazdadb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mazdadb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mazdadb`.`Employee` (
  `Emp_SSN` CHAR(9) NOT NULL,
  `Salary` DECIMAL(10,2) NULL DEFAULT NULL,
  `Position` CHAR(40) NULL DEFAULT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Middle_Initial` CHAR(1) NULL,
  `Last_Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Emp_SSN`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mazdadb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mazdadb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mazdadb`.`Customer` (
  `License_ID` CHAR(9) NOT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Middle_Initial` CHAR(1) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Phone` VARCHAR(15) NULL,
  PRIMARY KEY (`License_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mazdadb`.`Offered_Vehicles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mazdadb`.`Offered_Vehicles` ;

CREATE TABLE IF NOT EXISTS `mazdadb`.`Offered_Vehicles` (
  `VIN` CHAR(17) NOT NULL,
  `Price` INT NULL,
  PRIMARY KEY (`VIN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mazdadb`.`Parts_Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mazdadb`.`Parts_Inventory` ;

CREATE TABLE IF NOT EXISTS `mazdadb`.`Parts_Inventory` (
  `Part_ID` CHAR(20) NOT NULL,
  `Count` INT NULL,
  `Part_Name` VARCHAR(60) NULL,
  `Unit_Price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`Part_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mazdadb`.`Part_Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mazdadb`.`Part_Orders` ;

CREATE TABLE IF NOT EXISTS `mazdadb`.`Part_Orders` (
  `Emp_SSN` CHAR(9) NULL,
  `Order_ID` INT NOT NULL,
  `Part_ID` CHAR(20) NULL,
  `Count` INT NULL,
  `Order_Date` DATE NULL,
  PRIMARY KEY (`Order_ID`),
  INDEX `Emp_SSN_idx` (`Emp_SSN` ASC) VISIBLE,
  INDEX `Part_ID_idx` (`Part_ID` ASC) VISIBLE,
  CONSTRAINT `Emp_SSN`
    FOREIGN KEY (`Emp_SSN`)
    REFERENCES `mazdadb`.`Employee` (`Emp_SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Part_ID`
    FOREIGN KEY (`Part_ID`)
    REFERENCES `mazdadb`.`Parts_Inventory` (`Part_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mazdadb`.`Service_Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mazdadb`.`Service_Request` ;

CREATE TABLE IF NOT EXISTS `mazdadb`.`Service_Request` (
  `Request_ID` INT NOT NULL,
  `License_ID` CHAR(9) NULL,
  `VIN` CHAR(17) NULL,
  `Price` DECIMAL(10,2) NULL,
  `Purpose` VARCHAR(100) NULL,
  `Status` VARCHAR(20) NULL,
  `Start_Date` DATE NULL,
  `Finish_Date` DATE NULL,
  PRIMARY KEY (`Request_ID`),
  INDEX `VIN_idx` (`VIN` ASC) VISIBLE,
  INDEX `License_ID_idx` (`License_ID` ASC) VISIBLE,
  CONSTRAINT `VIN`
    FOREIGN KEY (`VIN`)
    REFERENCES `mazdadb`.`Offered_Vehicles` (`VIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `License_ID`
    FOREIGN KEY (`License_ID`)
    REFERENCES `mazdadb`.`Customer` (`License_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mazdadb`.`Service_Parts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mazdadb`.`Service_Parts` ;

CREATE TABLE IF NOT EXISTS `mazdadb`.`Service_Parts` (
  `Request_ID` INT NOT NULL,
  `Part_ID` CHAR(20) NULL,
  `Count` INT NULL,
  PRIMARY KEY (`Request_ID`, 'Part_ID'), --composite primary key in case service request has multiple part, but duplicate req ID
  INDEX `Parts_ID_idx` (`Part_ID` ASC) VISIBLE,
  CONSTRAINT `Request_ID`
    FOREIGN KEY (`Request_ID`)
    REFERENCES `mazdadb`.`Service_Request` (`Request_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Parts_ID`
    FOREIGN KEY (`Part_ID`)
    REFERENCES `mazdadb`.`Parts_Inventory` (`Part_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mazdadb`.`Customer_Vehical_Ownership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mazdadb`.`Customer_Vehical_Ownership` ;

CREATE TABLE IF NOT EXISTS `mazdadb`.`Customer_Vehical_Ownership` (
  `VIN` CHAR(17) NULL,
  `License_ID` CHAR(9) NULL,
  INDEX `VIN_idx` (`VIN` ASC) VISIBLE,
  INDEX `License_ID_idx` (`License_ID` ASC) VISIBLE,
  CONSTRAINT `VIN`
    FOREIGN KEY (`VIN`)
    REFERENCES `mazdadb`.`Offered_Vehicles` (`VIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `License_ID`
    FOREIGN KEY (`License_ID`)
    REFERENCES `mazdadb`.`Customer` (`License_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mazdadb`.`Vehicle_Sales_Leases_Finances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mazdadb`.`Vehicle_Sales_Leases_Finances` ;

CREATE TABLE IF NOT EXISTS `mazdadb`.`Vehicle_Sales_Leases_Finances` (
  `Trans_ID` INT NOT NULL,
  `License_ID` CHAR(9) NULL,
  `VIN` CHAR(17) NULL,
  `Emp_SSN` CHAR(9) NULL,
  `Terms` VARCHAR(100) NULL,
  `Amount` DECIMAL(10,2) NULL,
  `Trans_Date` DATE NULL,
  `Trans_Type` VARCHAR(10) NULL,
  PRIMARY KEY (`Trans_ID`),
  INDEX `License_ID_idx` (`License_ID` ASC) VISIBLE,
  INDEX `VIN_idx` (`VIN` ASC) VISIBLE,
  INDEX `Emp_SSN_idx` (`Emp_SSN` ASC) VISIBLE,
  CONSTRAINT `License_ID`
    FOREIGN KEY (`License_ID`)
    REFERENCES `mazdadb`.`Customer` (`License_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VIN`
    FOREIGN KEY (`VIN`)
    REFERENCES `mazdadb`.`Offered_Vehicles` (`VIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Emp_SSN`
    FOREIGN KEY (`Emp_SSN`)
    REFERENCES `mazdadb`.`Employee` (`Emp_SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mazdadb`.`Employee_Assignments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mazdadb`.`Employee_Assignments` ;

CREATE TABLE IF NOT EXISTS `mazdadb`.`Employee_Assignments` (
  `Request_ID` INT NULL,
  `Emp_SSN` CHAR(9) NULL,
  INDEX `Request_idx` (`Request_ID` ASC) VISIBLE,
  INDEX `Emp_SSN_idx` (`Emp_SSN` ASC) VISIBLE,
  CONSTRAINT `Request`
    FOREIGN KEY (`Request_ID`)
    REFERENCES `mazdadb`.`Service_Request` (`Request_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Emp_SSN`
    FOREIGN KEY (`Emp_SSN`)
    REFERENCES `mazdadb`.`Employee` (`Emp_SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mazdadb`.`Part_Sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mazdadb`.`Part_Sales` ;

CREATE TABLE IF NOT EXISTS `mazdadb`.`Part_Sales` (
  `Part_Sale_ID` INT NOT NULL,
  `License_ID` CHAR(9) NULL,
  `Part_ID` CHAR(20) NULL,
  `Emp_SSN` CHAR(9) NULL,
  `Count` INT NULL,
  `Amount` DECIMAL(10,2) NULL,
  `Sale_Date` DATE NULL,
  PRIMARY KEY (`Part_Sale_ID`),
  INDEX `License_IS_idx` (`License_ID` ASC) VISIBLE,
  INDEX `Emp_SSN_idx` (`Emp_SSN` ASC) VISIBLE,
  CONSTRAINT `License_ID`
    FOREIGN KEY (`License_ID`)
    REFERENCES `mazdadb`.`Customer` (`License_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Part_ID_Sales`
    FOREIGN KEY ('Part_ID')
    REFERENCES `mazdadb`.`Employee` ('Part_ID')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Emp_SSN`
    FOREIGN KEY (`Emp_SSN`)
    REFERENCES `mazdadb`.`Employee` (`Emp_SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mazdadb`.`Sent_Invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mazdadb`.`Sent_Invoices` ;

CREATE TABLE IF NOT EXISTS `mazdadb`.`Sent_Invoices` (
  `Invoice_ID` INT NOT NULL,
  `Emp_SSN` CHAR(9) NULL,
  `License_ID` CHAR(9) NULL,
  `Amount` DECIMAL(10,2) NULL,
  `Purpose` VARCHAR(100) NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`Invoice_ID`),
  INDEX `Emp_SSN_idx` (`Emp_SSN` ASC) VISIBLE,
  INDEX `License_ID_idx` (`License_ID` ASC) VISIBLE,
  CONSTRAINT `Emp_SSN`
    FOREIGN KEY (`Emp_SSN`)
    REFERENCES `mazdadb`.`Employee` (`Emp_SSN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `License_ID`
    FOREIGN KEY (`License_ID`)
    REFERENCES `mazdadb`.`Customer` (`License_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
